import {
  REGION_FRAGMENT_KEY,
  base64UrlDecode,
  base64UrlEncode,
  canonicalRegionJson,
  parseRegionJson,
  validateRegion,
  type NotabilityRegionV1
} from "./model";

const NOTE_PATH = /^\/app\/note\/([0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})\/?$/i;
const ALLOWED_HOSTS = new Set(["notability.com", "www.notability.com"]);

export const INTERNAL_REGION_PROTOCOL = "obsidian:";
export const INTERNAL_REGION_ACTION = "notability-live-region";
export const INTERNAL_REGION_PARAMETER = "region";
export const MAX_ENCODED_REGION_LENGTH = 8_192;

const BASE64URL = /^[A-Za-z0-9_-]+$/;
const MAX_LINK_URL_LENGTH = MAX_ENCODED_REGION_LENGTH + 256;

export class UrlPolicyError extends Error {}

export function isAllowedNotabilityOrigin(value: string): boolean {
  try {
    const url = new URL(value);
    return url.protocol === "https:"
      && ALLOWED_HOSTS.has(url.hostname.toLowerCase())
      && !url.username
      && !url.password
      && !url.port;
  } catch {
    return false;
  }
}

/** Return the one canonical URL used inside new region metadata. */
export function sanitizeNotabilityNoteUrl(value: string): string {
  let url: URL;
  try {
    url = new URL(value.trim());
  } catch {
    throw new UrlPolicyError("Enter a valid Notability note URL.");
  }
  if (url.protocol !== "https:" || !ALLOWED_HOSTS.has(url.hostname.toLowerCase())) {
    throw new UrlPolicyError("Only HTTPS Notability note URLs are allowed.");
  }
  if (url.username || url.password) throw new UrlPolicyError("Credential-bearing URLs are refused.");
  if (url.port) throw new UrlPolicyError("Non-default ports are refused.");
  const match = NOTE_PATH.exec(url.pathname);
  if (!match?.[1]) {
    throw new UrlPolicyError("The URL must identify one Notability note.");
  }
  return `https://notability.com/app/note/${match[1].toLowerCase()}`;
}

export function extractNoteId(value: string): string {
  const url = new URL(sanitizeNotabilityNoteUrl(value));
  const match = NOTE_PATH.exec(url.pathname);
  if (!match?.[1]) throw new UrlPolicyError("Notability note identity is missing.");
  return match[1].toLowerCase();
}

function canonicalLinkedRegion(value: NotabilityRegionV1): NotabilityRegionV1 {
  const region = validateRegion(value);
  return {
    ...region,
    url: sanitizeNotabilityNoteUrl(region.url)
  };
}

/** Compact, stable JSON used only in the new internal Obsidian URL. */
export function compactCanonicalRegionJson(region: NotabilityRegionV1): string {
  return JSON.stringify(canonicalLinkedRegion(region));
}

function encodeInternalRegionPayload(region: NotabilityRegionV1): string {
  const encoded = base64UrlEncode(compactCanonicalRegionJson(region));
  if (encoded.length > MAX_ENCODED_REGION_LENGTH) {
    throw new UrlPolicyError("The Notability region link is too large.");
  }
  return encoded;
}

function decodeCanonicalBase64Url(value: string): string | null {
  if (!value || value.length > MAX_ENCODED_REGION_LENGTH || !BASE64URL.test(value)) return null;
  try {
    const decoded = base64UrlDecode(value);
    return base64UrlEncode(decoded) === value ? decoded : null;
  } catch {
    return null;
  }
}

/** Generate an app-owned URL. New Markdown must never contain the Notability web URL. */
export function regionMarkdownUrl(region: NotabilityRegionV1): string {
  return `${INTERNAL_REGION_PROTOCOL}//${INTERNAL_REGION_ACTION}?${INTERNAL_REGION_PARAMETER}=${encodeInternalRegionPayload(region)}`;
}

/** Strict parser for the app-owned URL generated by regionMarkdownUrl. */
export function parseInternalRegionMarkdownUrl(value: string): NotabilityRegionV1 | null {
  if (!value || value.length > MAX_LINK_URL_LENGTH || value.trim() !== value || value.includes("#")) return null;
  let url: URL;
  try {
    url = new URL(value);
  } catch {
    return null;
  }
  if (
    url.protocol !== INTERNAL_REGION_PROTOCOL
    || url.hostname !== INTERNAL_REGION_ACTION
    || (url.pathname !== "" && url.pathname !== "/")
    || url.username
    || url.password
    || url.port
    || url.hash
  ) return null;

  const entries = [...url.searchParams.entries()];
  if (entries.length !== 1 || entries[0]?.[0] !== INTERNAL_REGION_PARAMETER) return null;
  const payload = entries[0][1];
  if (url.search !== `?${INTERNAL_REGION_PARAMETER}=${payload}`) return null;
  const canonicalWithoutSlash = `${INTERNAL_REGION_PROTOCOL}//${INTERNAL_REGION_ACTION}?${INTERNAL_REGION_PARAMETER}=${payload}`;
  const canonicalWithSlash = `${INTERNAL_REGION_PROTOCOL}//${INTERNAL_REGION_ACTION}/?${INTERNAL_REGION_PARAMETER}=${payload}`;
  if (value !== canonicalWithoutSlash && value !== canonicalWithSlash) return null;
  const decoded = decodeCanonicalBase64Url(payload);
  if (decoded === null) return null;

  try {
    const region = parseRegionJson(decoded);
    const canonical = canonicalLinkedRegion(region);
    if (region.url !== canonical.url || decoded !== JSON.stringify(canonical)) return null;
    return canonical;
  } catch {
    return null;
  }
}

/** Decode the query object supplied by Obsidian's registered protocol handler. */
export function parseInternalRegionProtocolParams(params: Record<string, string>): NotabilityRegionV1 | null {
  const keys = Object.keys(params).filter((key) => key !== "action");
  if (keys.length !== 1 || keys[0] !== INTERNAL_REGION_PARAMETER) return null;
  if (params.action !== undefined && params.action !== INTERNAL_REGION_ACTION) return null;
  const payload = params[INTERNAL_REGION_PARAMETER];
  if (!payload || !BASE64URL.test(payload)) return null;
  return parseInternalRegionMarkdownUrl(
    `${INTERNAL_REGION_PROTOCOL}//${INTERNAL_REGION_ACTION}?${INTERNAL_REGION_PARAMETER}=${payload}`
  );
}

/**
 * Read-only compatibility for links emitted by v0.1. These links are accepted
 * so existing notes keep working, but no formatter calls this format.
 */
export function parseLegacyRegionMarkdownUrl(value: string): NotabilityRegionV1 | null {
  if (!value || value.length > MAX_LINK_URL_LENGTH || value.trim() !== value) return null;
  let url: URL;
  try {
    url = new URL(value);
  } catch {
    return null;
  }
  if (
    url.protocol !== "https:"
    || url.hostname !== "notability.com"
    || url.username
    || url.password
    || url.port
    || url.search
    || !NOTE_PATH.test(url.pathname)
  ) return null;

  const prefix = `#${REGION_FRAGMENT_KEY}=`;
  if (!url.hash.startsWith(prefix)) return null;
  const payload = url.hash.slice(prefix.length);
  const decoded = decodeCanonicalBase64Url(payload);
  if (decoded === null) return null;

  try {
    const region = parseRegionJson(decoded);
    if (decoded !== canonicalRegionJson(region).trimEnd()) return null;
    if (sanitizeNotabilityNoteUrl(region.url) !== sanitizeNotabilityNoteUrl(value)) return null;
    return region;
  } catch {
    return null;
  }
}

/** Parse either the current internal URL or a strictly valid legacy URL. */
export function parseRegionMarkdownUrl(value: string): NotabilityRegionV1 | null {
  return parseInternalRegionMarkdownUrl(value) ?? parseLegacyRegionMarkdownUrl(value);
}

export function normalizeMarkdownLinkLabel(value: string): string {
  return value.replace(/[\p{Cc}\s]+/gu, " ").trim();
}

export function escapeMarkdownLinkLabel(value: string): string {
  return value
    .replace(/\\/g, "\\\\")
    .replace(/\[/g, "\\[")
    .replace(/\]/g, "\\]");
}

export function defaultRegionLabel(region: NotabilityRegionV1): string {
  const title = normalizeMarkdownLinkLabel(region.title) || "Notability note";
  return `${title}, p. ${region.page}`;
}

/** Transient PDF text becomes a concise fallback label, never stable metadata. */
export function textSelectionLabel(value: string, maxCharacters = 160): string {
  const normalized = value.replace(/[\r\n\t ]+/g, " ").trim();
  if (!normalized || !Number.isInteger(maxCharacters) || maxCharacters < 1) return "";
  return [...normalized].slice(0, maxCharacters).join("");
}

export function markdownRegionLink(label: string, region: NotabilityRegionV1): string {
  const normalized = normalizeMarkdownLinkLabel(label) || defaultRegionLabel(region);
  return `[${escapeMarkdownLinkLabel(normalized)}](${regionMarkdownUrl(region)})`;
}

export function redactUrl(value: string): string {
  try {
    const url = new URL(value);
    return `${url.origin}${url.pathname}`;
  } catch {
    return "[invalid URL]";
  }
}
